# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec767ae540fa8d433ad21929db1112d3606ba2cd8952b9bca7a2bbabc50b1c834eae151bce7c32823edd30f5a2848416edf6f9af6133f4398555960ebd6e4afb

test:
  secret_key_base: 14646dcb4fda4e909524bbc0b0cbfd1cdae329516daa94b0e7c7ac03c0d3213e12138d9ab68b4c75627f90d1d6f370b5dd7239909de2f3b67e3ff05a1dea2a57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
